trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - script: echo "Building the application..."

- stage: Dev
  displayName: 'Dev'
  jobs:
  - job: Dev
    displayName: 'Dev Job'
    steps:
    - script: echo "Running Dev tasks..."

- stage: Test
  displayName: 'Test'
  jobs:
  - job: Test
    displayName: 'Test Job'
    steps:
    - script: echo "Running Test tasks..."

- stage: SIT
  displayName: 'SIT'
  jobs:
  - job: SIT
    displayName: 'SIT Job'
    steps:
    - script: echo "Running SIT tasks..."

- stage: Preprod
  displayName: 'Preprod'
  jobs:
  - job: Preprod
    displayName: 'Preprod Job'
    steps:
    - script: echo "Running Preprod tasks..."

- stage: Prod
  displayName: 'Prod'
  jobs:
  - job: Prod
    displayName: 'Prod Job'
    steps:
    - script: echo "Running Prod tasks..."

